-- ========================================
-- ========== Malcom's Tables ============
-- ========================================

-- MySQL Script generated by MySQL Workbench
-- Mon Mar 31 13:19:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Admin (Only us 4)
-- -----------------------------------------------------
-- Table admininfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS`admininfo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MemberName` VARCHAR(255) NULL DEFAULT 'unknown',
  `E_mail` VARCHAR(255) NULL DEFAULT 'user@mail.com',
  `PhoneNum` VARCHAR(15) NULL DEFAULT '0000000000',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- baseuser: All base users (key members, company members, etc.)
-- -----------------------------------------------------
-- Table `baseuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseuser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(100) NOT NULL,
  `userEmail` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `UserAddress` TEXT NULL DEFAULT NULL,
  `UserPhone` VARCHAR(20) NULL DEFAULT NULL,
  `isKeyMember` TINYINT(1) NULL DEFAULT '0',
  `dateAccountMade` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `eventsHosted` INT NULL DEFAULT '0',
  `eventsAttended` INT NULL DEFAULT '0',
  `interest1` VARCHAR(100) NULL DEFAULT NULL,
  `interest2` VARCHAR(100) NULL DEFAULT NULL,
  `interest3` VARCHAR(100) NULL DEFAULT NULL,
  `memberID` INT NOT NULL,
  `timesWorkspaceReserved` INT NULL DEFAULT '0',
  `benefitProgress` INT NOT NULL DEFAULT '0',
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  `membershipType` ENUM('Community Member', 'Key Access Member', 'Workspace Member') NULL DEFAULT 'Community Member',
  `basedOn` ENUM('Individual', 'Company') NULL DEFAULT 'Individual',
  `tag` ENUM('Usually', 'Often', 'Always', 'Never') NULL DEFAULT 'Usually',
  `status` ENUM('Approved', 'Denied', 'Waiting') NOT NULL DEFAULT 'Waiting',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userEmail` (`userEmail` ASC) VISIBLE,
  UNIQUE INDEX `memberID` (`memberID` ASC) VISIBLE,
  UNIQUE INDEX `UserPhone` (`UserPhone` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `companies` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(255) NOT NULL,
  `leader` VARCHAR(255) NOT NULL,
  `companyAddress` VARCHAR(255) NULL DEFAULT NULL,
  `companyPhone` VARCHAR(20) NULL DEFAULT NULL,
  `companyEmail` VARCHAR(255) NULL DEFAULT NULL,
  `companyWebsite` VARCHAR(255) NULL DEFAULT NULL,
  `memberCountUsingTC` INT NULL DEFAULT NULL,
  `companyBio` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`company_id`),
  UNIQUE INDEX `companyName` (`companyName` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- Company roles: Links baseuser to companies with specific roles
-- -----------------------------------------------------
-- Table `company_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company_roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `memberID` INT NOT NULL,
  `company_id` INT NOT NULL,
  `role` VARCHAR(100) NOT NULL,
  `area` ENUM('Management', 'Leadership', 'HR', 'Marketing', 'Finance', 'Sales', 'Product Development', 'Support Staff', 'Other') NOT NULL,
  `is_company_admin` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`role_id`),
  INDEX `memberID` (`memberID` ASC) VISIBLE,
  INDEX `company_id` (`company_id` ASC) VISIBLE,
  CONSTRAINT `company_roles_ibfk_1`
    FOREIGN KEY (`memberID`)
    REFERENCES `dwa`.`baseuser` (`memberID`)
    ON DELETE CASCADE,
  CONSTRAINT `company_roles_ibfk_2`
    FOREIGN KEY (`company_id`)
    REFERENCES `dwa`.`companies` (`company_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



                                -- Calendar: Events table
                                CREATE TABLE Calendar
                                (
                                        event_id INT
                                        AUTO_INCREMENT PRIMARY KEY,  -- Unique event identifier
    title VARCHAR
                                        (255) NOT NULL,              -- Event title
    description TEXT,                         -- Event details
    image_url VARCHAR
                                        (255) NOT NULL,          -- Event image URL
    start_date DATE NOT NULL,                 -- Event start date
    end_date DATE NOT NULL,                   -- Event end date
    start_time TIME NOT NULL,                 -- Event start time
    end_time TIME NOT NULL,                   -- Event end time
    recurrence ENUM
                                        ('none','daily','weekly','monthly') DEFAULT 'none',
    visibility ENUM
                                        ('public','private','members-only') DEFAULT 'public'
);

                                        -- EventAttendees: Records which user joined which event
                                        CREATE TABLE EventAttendees
                                        (
                                                attendee_id INT
                                                AUTO_INCREMENT PRIMARY KEY,  -- Unique record for each attendee-event combination
    event_id INT NOT NULL,                       -- Links to Calendar table
    user_id INT NOT NULL,                        -- Links to BaseUser table
    status ENUM
                                                ('attending','maybe','declined') DEFAULT 'attending',
    CONSTRAINT fk_event FOREIGN KEY
                                                (event_id) REFERENCES Calendar
                                                (event_id) ON
                                                DELETE CASCADE,
    CONSTRAINT fk_user FOREIGN KEY
                                                (user_id) REFERENCES BaseUser
                                                (id) ON
                                                DELETE CASCADE
);

                                                -- ========================================
                                                -- ========== Support Requests ============
                                                -- ========================================
                                                CREATE TABLE support_request
                                                (
                                                        id INT
                                                        AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR
                                                        (100),
    email VARCHAR
                                                        (255),
    issue_type VARCHAR
                                                        (50),
    issue_description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
